### ISSUE TITLE
RFC line length is not support when encoding

### ISSUE THREAD

**Issue by dploeger** [emersion/go-ical#18]
As RFC5545 states:

> Lines of text SHOULD NOT be longer than 75 octets, excluding the line break. Long content lines SHOULD be split into a multiple line representations using a line "folding" technique. 

This is currently not supported. Lines are completely posted into the output without folding.

**Comment by emersion** [comment]
I would rather not. This is just a SHOULD. I've implemented it for go-message and it caused a ton of regressions. It's very tricky to get right.

**Comment by dploeger** [comment]
Ah, you're right. I couldn't import a calendar file from go-ical into Confluence Calendars but after all it wasn't the line length but something else. Fair enough.

**Comment by Dynom** [comment]
FWIW, I've been using this and I've not yet had any problems with it https://github.com/emersion/go-ical/compare/master...Dynom:go-ical:AddingLineFolding

I needed it because of a buggy implementation with an integration which had a hard fail on a surplus of 75 octets.

**Comment by dploeger** [comment]
Would you accept a PR from @Dynom about this, @emersion ?
